networks:
  elk:
    driver: bridge
    ipam:
      config:
        - subnet: 123.123.0.0/16

volumes:
  elastic_volume:
    driver: local
  kibana_volume:
    driver: local


services: 
  elastic:
    image: elasticsearch:8.0.1
    container_name: elastic
    tty: true
    restart: unless-stopped
    ports:
      - 9200:9200
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$ELASTIC_PASS
    networks:
      - elk
    healthcheck:
      test: curl -u $ELASTIC_USER:$ELASTIC_PASS -s -f localhost:9200/_cat/health >/dev/null || exit 1 
      timeout: 10s
      start_period: 30s
    
  kibana:
    image: kibana:8.0.1
    container_name: kibana
    tty: true
    restart: unless-stopped
    ports:
      - 5601:5601
    volumes:
      - kibana_volume:/usr/share/kibana
    networks:
      - elk
